version: '3.8'
services:
  db-mysql:
    image: mariadb:10.5.8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: poc
    command:
      ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  db-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: --loglevel warning
