spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jooq
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: passwd

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG